### ISSUE TITLE
libmozilla_voice_stt.so linked against macOS 10.15 instead of 10.10

### ISSUE THREAD

**Issue by Arpitrf** [mozilla/STT#3249] opened 2020-08-17 09:24 UTC
Hello,

I am getting the following error when running the below command. 

`**(deepspeechenv) 192:deepspeech apple$** deepspeech --model deepspeech-0.7.0-models.pbmm --scorer deepspeech-0.7.0-models.scorer --audio audio/2830-3980-0043.wav

Traceback (most recent call last):
  File "/Users/apple/Desktop/Citi/FRM/deepspeech/deepspeechenv/bin/deepspeech", line 5, in <module>
    from deepspeech.client import main
  File "/Users/apple/Desktop/Citi/FRM/deepspeech/deepspeechenv/lib/python3.6/site-packages/deepspeech/__init__.py", line 23, in <module>
    from deepspeech.impl import Version as version
  File "/Users/apple/Desktop/Citi/FRM/deepspeech/deepspeechenv/lib/python3.6/site-packages/deepspeech/impl.py", line 13, in <module>
    from . import _impl
ImportError: dlopen(/Users/apple/Desktop/Citi/FRM/deepspeech/deepspeechenv/lib/python3.6/site-packages/deepspeech/_impl.cpython-36m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/apple/Desktop/Citi/FRM/deepspeech/deepspeechenv/lib/python3.6/site-packages/deepspeech/lib/libdeepspeech.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/apple/Desktop/Citi/FRM/deepspeech/deepspeechenv/lib/python3.6/site-packages/deepspeech/lib/libdeepspeech.so`

**Comment by lissyx** [comment] 2020-08-17 09:31
Please document what version that is, because we force targetting à lower version...

**Comment by lissyx** [comment] 2020-08-17 09:44
Here, 10.10: https://github.com/mozilla/STT/blob/master/taskcluster/darwin-opt-base.tyml#L52

So I don't know why it would require 10.15 ...

**Comment by Arpitrf** [comment] 2020-08-17 10:15
deepspeech version: 0.8.1
Python version: Python 3.6.5
pip version: pip 20.2.2

**Comment by Arpitrf** [comment] 2020-08-17 10:27
Ok I found a work-around.

pip uninstall deepspeech
pip install deepspeech==0.7.0

Version 0.7.0 works. 

Is deepseech version 0.8.1 incompatible with macOS?

**Comment by lissyx** [comment] 2020-08-17 10:28
> Is deepseech version 0.8.1 incompatible with macOS?

Did you read my replies? It should not.

**Comment by lissyx** [comment] 2020-08-17 10:30
@Arpitrf Please, can you check with `native_client.tar.xz`, to check if it is `libdeepspeech.so` build or just the Python wrapper.

**Comment by Arpitrf** [comment] 2020-08-17 10:32
I am sorry I did not understand the above.

**Comment by lissyx** [comment] 2020-08-17 10:35
https://github.com/mozilla/STT/releases/download/v0.8.1/native_client.amd64.cpu.osx.tar.xz

**Comment by Arpitrf** [comment] 2020-08-17 10:39
This installed this - native_client.amd64.cpu.osx.tar.xz. What to do next?

**Comment by lissyx** [comment] 2020-08-17 10:42
> This installed this - native_client.amd64.cpu.osx.tar.xz. What to do next?

Extract and run `./deepspeech --version` to see if you have the same problem?

**Comment by Arpitrf** [comment] 2020-08-17 10:51
> Extract and run `./deepspeech --version` to see if you have the same problem?

Output: DeepSpeech 0.8.1

**Comment by lissyx** [comment] 2020-08-17 10:51
> > Extract and run `./deepspeech --version` to see if you have the same problem?
> 
> Output: DeepSpeech 0.8.1

Can you try to run a model then?
```
./deepspeech --model deepspeech-0.7.0-models.pbmm --scorer deepspeech-0.7.0-models.scorer --audio audio/2830-3980-0043.wav
```

**Comment by lissyx** [comment] 2020-08-18 11:21
@Arpitrf Please?

**Comment by Arpitrf** [comment] 2020-08-18 12:20
Still does not work.

`**(deepspeechenv) 192:deepspeech apple$** ./deepspeech --model deepspeech-0.7.0-models.pbmm --scorer deepspeech-0.7.0-models.scorer --audio audio/2830-3980-0043.wav

TensorFlow: v2.2.0-24-g1c1b2b9dd9
DeepSpeech: v0.8.1-0-gfa883eb8
2020-08-18 17:48:29.840025: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/apple/Desktop/Citi/FRM/deepspeech/libdeepspeech.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/apple/Desktop/Citi/FRM/deepspeech/libdeepspeech.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
`

**Comment by lissyx** [comment] 2020-08-18 13:00
> dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
> Referenced from: /Users/apple/Desktop/Citi/FRM/deepspeech/libdeepspeech.so (which was built for Mac OS X 10.15)

Thanks, so I fear this is a regression from using XCode for iOS support :/ cc @reuben 

There's an upstream Bazel bug matching that, where Bazel does not respect minimum sdk we force, but it was only fixed in 3.4 and TensorFlow r2.2 used for r0.8 uses Bazel 2.0.0, and I don't see any workaround so far.

We just upgraded master to r2.3, but:
 - it is using Bazel 3.1, not 3.4
 - if it fixes, it requires complete rebuild of TensorFlow and our macOS CI is not really in good shape.

I'm unsure if we can fix that soonish.

**Comment by lissyx** [comment] 2020-08-18 13:04
Also, changing Bazel version is kind of invasive, I'm not sure we want to do that on 0.8 ...

**Comment by Arpitrf** [comment] 2020-08-18 17:31
Thanks for your help!

**Comment by lissyx** [comment] 2020-08-19 12:03
Turns out @reuben might have found a proper fix that is not invasive as we first tought, but it will require some full rebuild so it may take a few days. Hopefully we might do 0.8.2 to ship it.

**Comment by lissyx** [comment] 2020-08-19 22:44
Fixed in master: https://github.com/mozilla/STT/pull/3259

**Comment by lissyx** [comment] 2020-08-20 08:06
And r0.8: #3260

**Closed by lissyx** 2020-08-20 08:06 UTC
Labels: bug
